/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5p2_edgarmembrenoo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author edgarmembreno
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a_jugador = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombreJugador = new javax.swing.JTextField();
        apellidoJugador = new javax.swing.JTextField();
        nacionalidadJugador = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        partidosJugador = new javax.swing.JTextField();
        copasJugador = new javax.swing.JTextField();
        tarjetasJugador = new javax.swing.JTextField();
        tarjetasAmarillas = new javax.swing.JTextField();
        contratoJugador = new javax.swing.JTextField();
        numeroJugador = new javax.swing.JTextField();
        Agregar_Jugador = new javax.swing.JButton();
        jd_Tree = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtree = new javax.swing.JTree();
        a_Entrenador = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        nombreEntrenador = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        apellidoEntrenador = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nacionalidadEntrenador = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        contratoEntrenador = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        copasEntrenador = new javax.swing.JTextField();
        entrenadorAgregar = new javax.swing.JButton();
        a_preparadores = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        nombrePreparador = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        apellidoPrepa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        nacionalidadPrepa = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        contratoPrepa = new javax.swing.JTextField();
        edadPrepa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        id_Prepa = new javax.swing.JTextField();
        especialidadPrepa = new javax.swing.JTextField();
        Titulo_Prepa = new javax.swing.JTextField();
        agregar_prepa = new javax.swing.JButton();
        a_psicologo = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        nombrePsico = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        apellidoPsico = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        nacionalidadPsico = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        contratoPsico = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        edadPsico = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        id_Psico = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        especialidadPsico = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        Titulo_Psico = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jugadores_Psico = new javax.swing.JTextField();
        a_psico = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        InformesGene = new javax.swing.JTextField();
        menuPop = new javax.swing.JPopupMenu();
        eliminar = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        Listar = new javax.swing.JMenuItem();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        agregar_jugador = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        agregar_entrenador = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        agregar_preparador = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        agregar_psicologo = new javax.swing.JMenuItem();
        opcion_arbol = new javax.swing.JMenuItem();

        a_jugador.setTitle("Agregar Jugador");

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Nacionalidad");

        jLabel4.setText("Edad");

        jLabel5.setText("Numero de Camisa");

        jLabel6.setText("Partidos Jugados");

        jLabel7.setText("Copas Ganadas");

        jLabel8.setText("Tarjetas Rojas");

        jLabel9.setText("Tarjetas Amarillas");

        jLabel10.setText("Contrato");

        nacionalidadJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadJugadorActionPerformed(evt);
            }
        });

        Agregar_Jugador.setText("Agregar");
        Agregar_Jugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_JugadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout a_jugadorLayout = new javax.swing.GroupLayout(a_jugador.getContentPane());
        a_jugador.getContentPane().setLayout(a_jugadorLayout);
        a_jugadorLayout.setHorizontalGroup(
            a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_jugadorLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(69, 69, 69)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agregar_Jugador)
                    .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(apellidoJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(nombreJugador)
                        .addComponent(nacionalidadJugador)
                        .addComponent(numeroJugador)
                        .addComponent(partidosJugador)
                        .addComponent(copasJugador)
                        .addComponent(tarjetasJugador)
                        .addComponent(tarjetasAmarillas)
                        .addComponent(contratoJugador)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        a_jugadorLayout.setVerticalGroup(
            a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_jugadorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(apellidoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nacionalidadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numeroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(partidosJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(copasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tarjetasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tarjetasAmarillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(contratoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(Agregar_Jugador)
                .addGap(23, 23, 23))
        );

        jd_Tree.setTitle("Arbol");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        jtree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtree);

        javax.swing.GroupLayout jd_TreeLayout = new javax.swing.GroupLayout(jd_Tree.getContentPane());
        jd_Tree.getContentPane().setLayout(jd_TreeLayout);
        jd_TreeLayout.setHorizontalGroup(
            jd_TreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jd_TreeLayout.setVerticalGroup(
            jd_TreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_TreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel11.setText("Nombre");

        jLabel12.setText("Apellido");

        jLabel13.setText("Nacionalidad");

        nacionalidadEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadEntrenadorActionPerformed(evt);
            }
        });

        jLabel14.setText("Edad");

        jLabel15.setText("Contrato");

        jLabel16.setText("Copas Ganadas");

        entrenadorAgregar.setText("Agregar");
        entrenadorAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrenadorAgregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout a_EntrenadorLayout = new javax.swing.GroupLayout(a_Entrenador.getContentPane());
        a_Entrenador.getContentPane().setLayout(a_EntrenadorLayout);
        a_EntrenadorLayout.setHorizontalGroup(
            a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_EntrenadorLayout.createSequentialGroup()
                .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(a_EntrenadorLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, a_EntrenadorLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(apellidoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, a_EntrenadorLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(nombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(a_EntrenadorLayout.createSequentialGroup()
                                .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(56, 56, 56)
                                .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contratoEntrenador)
                                    .addComponent(copasEntrenador)
                                    .addGroup(a_EntrenadorLayout.createSequentialGroup()
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(nacionalidadEntrenador)))))
                    .addGroup(a_EntrenadorLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(entrenadorAgregar)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        a_EntrenadorLayout.setVerticalGroup(
            a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_EntrenadorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(a_EntrenadorLayout.createSequentialGroup()
                        .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(apellidoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(nacionalidadEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14))
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(copasEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_EntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(contratoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(entrenadorAgregar)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel18.setText("Nombre");

        jLabel19.setText("Apellido");

        jLabel20.setText("Nacionalidad");

        nacionalidadPrepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadPrepaActionPerformed(evt);
            }
        });

        jLabel21.setText("Contrato");

        jLabel22.setText("Edad");

        jLabel23.setText("ID");

        jLabel24.setText("Especialidad");

        jLabel25.setText("Titulo");

        agregar_prepa.setText("Agregar");
        agregar_prepa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_prepaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout a_preparadoresLayout = new javax.swing.GroupLayout(a_preparadores.getContentPane());
        a_preparadores.getContentPane().setLayout(a_preparadoresLayout);
        a_preparadoresLayout.setHorizontalGroup(
            a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_preparadoresLayout.createSequentialGroup()
                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(a_preparadoresLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(a_preparadoresLayout.createSequentialGroup()
                                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addGap(9, 9, 9))
                            .addComponent(jLabel24))
                        .addGap(56, 56, 56)
                        .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombrePreparador, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(apellidoPrepa, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(nacionalidadPrepa)
                            .addComponent(contratoPrepa)
                            .addComponent(edadPrepa)
                            .addComponent(id_Prepa)
                            .addComponent(especialidadPrepa)
                            .addComponent(Titulo_Prepa)))
                    .addGroup(a_preparadoresLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(agregar_prepa)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        a_preparadoresLayout.setVerticalGroup(
            a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_preparadoresLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nombrePreparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(apellidoPrepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(nacionalidadPrepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contratoPrepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(31, 31, 31)
                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edadPrepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(id_Prepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(a_preparadoresLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, a_preparadoresLayout.createSequentialGroup()
                        .addComponent(especialidadPrepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(a_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(Titulo_Prepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(agregar_prepa)
                .addGap(45, 45, 45))
        );

        jLabel27.setText("Nombre");

        jLabel28.setText("Apellido");

        jLabel29.setText("Nacionalidad");

        nacionalidadPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadPsicoActionPerformed(evt);
            }
        });

        jLabel30.setText("Contrato");

        jLabel31.setText("Edad");

        jLabel32.setText("ID");

        jLabel33.setText("Especialidad");

        jLabel34.setText("Titulo");

        jLabel35.setText("Jugadores Atendidos");

        a_psico.setText("Agregar");
        a_psico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_psicoMouseClicked(evt);
            }
        });

        jLabel26.setText("Informes ");

        javax.swing.GroupLayout a_psicologoLayout = new javax.swing.GroupLayout(a_psicologo.getContentPane());
        a_psicologo.getContentPane().setLayout(a_psicologoLayout);
        a_psicologoLayout.setHorizontalGroup(
            a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_psicologoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(a_psicologoLayout.createSequentialGroup()
                        .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel26))
                        .addGap(9, 9, 9)))
                .addGap(51, 51, 51)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(a_psico)
                    .addComponent(nombrePsico)
                    .addComponent(apellidoPsico)
                    .addComponent(nacionalidadPsico)
                    .addComponent(contratoPsico, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(edadPsico)
                    .addComponent(id_Psico)
                    .addComponent(especialidadPsico)
                    .addComponent(Titulo_Psico)
                    .addComponent(jugadores_Psico)
                    .addComponent(InformesGene))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        a_psicologoLayout.setVerticalGroup(
            a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_psicologoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(nombrePsico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(apellidoPsico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(nacionalidadPsico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contratoPsico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(22, 22, 22)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(edadPsico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(id_Psico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(especialidadPsico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(Titulo_Psico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jugadores_Psico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(a_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(InformesGene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(a_psico)
                .addGap(35, 35, 35))
        );

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        menuPop.add(eliminar);

        modificar.setText("Modificar");
        menuPop.add(modificar);

        Listar.setText("Listar");
        menuPop.add(Listar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel17.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel17.setText("Menu De Opciones");

        jMenu2.setText("Opciones");

        jMenu1.setText("Jugadores");

        agregar_jugador.setText("Agregar Jugador");
        agregar_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_jugadorActionPerformed(evt);
            }
        });
        jMenu1.add(agregar_jugador);

        jMenu2.add(jMenu1);

        jMenu3.setText("Entrenadores");

        agregar_entrenador.setText("Agregar Entrenador");
        agregar_entrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_entrenadorActionPerformed(evt);
            }
        });
        jMenu3.add(agregar_entrenador);

        jMenu2.add(jMenu3);

        jMenu4.setText("Preparadores");

        agregar_preparador.setText("Agregar Preparadores");
        agregar_preparador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_preparadorActionPerformed(evt);
            }
        });
        jMenu4.add(agregar_preparador);

        jMenu2.add(jMenu4);

        jMenu5.setText("Psicologos");

        agregar_psicologo.setText("Agregar Psicologo");
        agregar_psicologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_psicologoActionPerformed(evt);
            }
        });
        jMenu5.add(agregar_psicologo);

        jMenu2.add(jMenu5);

        opcion_arbol.setText("Arbol");
        opcion_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_arbolActionPerformed(evt);
            }
        });
        jMenu2.add(opcion_arbol);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel17)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregar_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_jugadorActionPerformed
        a_jugador.setModal(true);
        a_jugador.pack();
        a_jugador.setLocationRelativeTo(this);
        a_jugador.setVisible(true);


    }//GEN-LAST:event_agregar_jugadorActionPerformed

    private void agregar_entrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_entrenadorActionPerformed
        a_Entrenador.setModal(true);
        a_Entrenador.pack();
        a_Entrenador.setLocationRelativeTo(this);
        a_Entrenador.setVisible(true);


    }//GEN-LAST:event_agregar_entrenadorActionPerformed

    private void nacionalidadJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadJugadorActionPerformed

    private void Agregar_JugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_JugadorMouseClicked
        try {
            String nombre, apellido, nacionalidad;
            int edad, numerocami;
            int partidos = 0;
            int copas = 0;
            int tarjetasRoj = 0;
            int tarAmarilla = 0;
            int contrato = 0;

            nombre = nombreJugador.getText();
            apellido = apellidoJugador.getText();
            nacionalidad = nacionalidadJugador.getText();
            edad = (Integer) jSpinner1.getValue();
            numerocami = Integer.parseInt(numeroJugador.getText());
            partidos = Integer.parseInt(partidosJugador.getText());
            copas = Integer.parseInt(copasJugador.getText());
            tarjetasRoj = Integer.parseInt(tarjetasJugador.getText());
            tarAmarilla = Integer.parseInt(tarjetasAmarillas.getText());
            contrato = Integer.parseInt(contratoJugador.getText());

            jugador.add(new Jugadores(nombre, apellido, edad, numerocami, partidos, copas, tarjetasRoj, tarAmarilla, contrato, nacionalidad));

            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jtree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(nombre)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Jugadores(nombre, apellido, edad, numerocami, partidos, copas, tarjetasRoj, tarjetasRoj, contrato, nacionalidad));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                }
            }

            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode("Jugadores");
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Jugadores(nombre, apellido, edad, numerocami, partidos, copas, tarjetasRoj, tarjetasRoj, contrato, nacionalidad));
                n.add(p);
                raiz.add(n);
            }
            modeloARBOL.reload();
            JOptionPane.showMessageDialog(this, "Usuario fue Agregado");
            nombreJugador.setText("");
            apellidoJugador.setText("");
            nacionalidadJugador.setText("");
            a_jugador.setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }
    }//GEN-LAST:event_Agregar_JugadorMouseClicked

    private void opcion_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_arbolActionPerformed
        jd_Tree.setModal(true);
        jd_Tree.pack();
        jd_Tree.setLocationRelativeTo(this);
        jd_Tree.setVisible(true);
        jd_Tree.setVisible(false);


    }//GEN-LAST:event_opcion_arbolActionPerformed

    private void nacionalidadEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadEntrenadorActionPerformed

    private void entrenadorAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrenadorAgregarMouseClicked
        try {
            String nombre, apellido, nacionalidad;
            int edad = 0;
            int contrato = 0;
            int copas = 0;

            nombre = nombreEntrenador.getText();
            apellido = apellidoEntrenador.getText();
            nacionalidad = nacionalidadEntrenador.getText();
            edad = Integer.parseInt(copasEntrenador.getText());
            contrato = Integer.parseInt(contratoEntrenador.getText());
            copas = Integer.parseInt(copasEntrenador.getText());

            entrenador.add(new Entrenadores(nombre, apellido, nacionalidad, edad, contrato, copas));

            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jtree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(nombre)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Entrenadores(nombre, apellido, nacionalidad, edad, contrato, copas));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                }
            }

            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode("Entrenadores");
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Entrenadores(nombre, apellido, nacionalidad, edad, contrato, copas));
                n.add(p);
                raiz.add(n);
            }
            modeloARBOL.reload();

            nombreEntrenador.setText("");
            apellidoEntrenador.setText("");
            nacionalidadEntrenador.setText("");
            copasEntrenador.setText("");
            contratoEntrenador.setText("");
            a_Entrenador.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }

    }//GEN-LAST:event_entrenadorAgregarMouseClicked

    private void nacionalidadPrepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadPrepaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadPrepaActionPerformed

    private void agregar_prepaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_prepaMouseClicked
        try {
            String nombre, apellido, nacionalidad, especialidad, titulo;
            int id;
            int edad;
            int contrato = 0;

            nombre = nombrePreparador.getText();
            apellido = apellidoPrepa.getText();
            nacionalidad = nacionalidadPrepa.getText();
            titulo = Titulo_Prepa.getText();
            especialidad = especialidadPrepa.getText();
            id = Integer.parseInt(id_Prepa.getText());
            edad = Integer.parseInt(edadPrepa.getText());
            contrato = Integer.parseInt(contratoPrepa.getText());

            prepa.add(new Preparadores(nombre, apellido, nacionalidad, id, edad, contrato, especialidad, titulo));

            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jtree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(nombre)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Preparadores(nombre, apellido, nacionalidad, id, edad, contrato, especialidad, titulo));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                }
            }

            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode("Preparadores");
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Preparadores(nombre, apellido, nacionalidad, id, edad, contrato, especialidad, titulo));
                n.add(p);
                raiz.add(n);
            }
            modeloARBOL.reload();
            nombrePreparador.setText("");
            apellidoPrepa.setText("");
            nacionalidadPrepa.setText("");
            Titulo_Prepa.setText("");
            especialidadPrepa.setText("");
            id_Prepa.setText("");
            edadPrepa.setText("");
            contratoPrepa.getText();
            a_preparadores.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }
    }//GEN-LAST:event_agregar_prepaMouseClicked

    private void agregar_preparadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_preparadorActionPerformed
        a_preparadores.setModal(true);
        a_preparadores.pack();
        a_preparadores.setLocationRelativeTo(this);
        a_preparadores.setVisible(true);
        a_preparadores.setVisible(false);


    }//GEN-LAST:event_agregar_preparadorActionPerformed

    private void agregar_psicologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_psicologoActionPerformed
        a_psicologo.setModal(true);
        a_psicologo.pack();
        a_psicologo.setLocationRelativeTo(this);
        a_psicologo.setVisible(true);
        a_psicologo.setVisible(false);


    }//GEN-LAST:event_agregar_psicologoActionPerformed

    private void nacionalidadPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadPsicoActionPerformed

    private void a_psicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_psicoMouseClicked
        try {
            String nombre, apellido, nacionalidad, titulo, especialidad;
            int edad, id, informes, jugaAten;

            nombre = nombrePsico.getText();
            apellido = apellidoPsico.getText();
            nacionalidad = nacionalidadPsico.getText();
            titulo = Titulo_Psico.getText();
            especialidad = especialidadPsico.getText();
            edad = Integer.parseInt(edadPsico.getText());
            id = Integer.parseInt(id_Psico.getText());
            informes = Integer.parseInt(InformesGene.getText());
            jugaAten = Integer.parseInt(jugadores_Psico.getText());

            psicolo.add(new Psicologo(nombre, apellido, nacionalidad, edad, titulo, id, especialidad, informes, jugaAten));

            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jtree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(nombre)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Psicologo(nombre, apellido, nacionalidad, edad, titulo, id, especialidad, informes, jugaAten));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                }
            }

            if (centinela == -1) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode("Psicologo");
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Psicologo(nombre, apellido, nacionalidad, edad, titulo, id, especialidad, informes, jugaAten));
                n.add(p);
                raiz.add(n);
            }
            modeloARBOL.reload();

            nombrePsico.setText("");
            apellidoPsico.setText("");
            nacionalidadPsico.setText("");
            Titulo_Psico.setText("");
            especialidadPsico.setText("");
            id_Psico.setText("");
            InformesGene.setText("");
            jugadores_Psico.setText("");
            a_psicologo.setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }

    }//GEN-LAST:event_a_psicoMouseClicked

    private void jtreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtreeMouseClicked
        if (evt.isMetaDown()) {
            int row = jtree.getClosestRowForLocation(evt.getX(), evt.getY());
            jtree.setSelectionRow(row);
            Object v1 = jtree.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;

            if (nodo_seleccionado.getUserObject() instanceof Jugadores) {
                juga_selec = (Jugadores) nodo_seleccionado.getUserObject();
                menuPop.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (nodo_seleccionado.getUserObject() instanceof Entrenadores) {
                entre_selec = (Entrenadores) nodo_seleccionado.getUserObject();
                menuPop.show(evt.getComponent(), evt.getX(), evt.getY());

            } else if (nodo_seleccionado.getUserObject() instanceof Preparadores) {
                prepa_selec = (Preparadores) nodo_seleccionado.getUserObject();
                menuPop.show(evt.getComponent(), evt.getX(), evt.getY());
                
            } else if (nodo_seleccionado.getUserObject() instanceof Psicologo) {
                psico_selec = (Psicologo) nodo_seleccionado.getUserObject();
                menuPop.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jtreeMouseClicked

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jtree.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Jugador;
    private javax.swing.JTextField InformesGene;
    private javax.swing.JMenuItem Listar;
    private javax.swing.JTextField Titulo_Prepa;
    private javax.swing.JTextField Titulo_Psico;
    private javax.swing.JDialog a_Entrenador;
    private javax.swing.JDialog a_jugador;
    private javax.swing.JDialog a_preparadores;
    private javax.swing.JButton a_psico;
    private javax.swing.JDialog a_psicologo;
    private javax.swing.JMenuItem agregar_entrenador;
    private javax.swing.JMenuItem agregar_jugador;
    private javax.swing.JButton agregar_prepa;
    private javax.swing.JMenuItem agregar_preparador;
    private javax.swing.JMenuItem agregar_psicologo;
    private javax.swing.JTextField apellidoEntrenador;
    private javax.swing.JTextField apellidoJugador;
    private javax.swing.JTextField apellidoPrepa;
    private javax.swing.JTextField apellidoPsico;
    private javax.swing.JTextField contratoEntrenador;
    private javax.swing.JTextField contratoJugador;
    private javax.swing.JTextField contratoPrepa;
    private javax.swing.JTextField contratoPsico;
    private javax.swing.JTextField copasEntrenador;
    private javax.swing.JTextField copasJugador;
    private javax.swing.JTextField edadPrepa;
    private javax.swing.JTextField edadPsico;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JButton entrenadorAgregar;
    private javax.swing.JTextField especialidadPrepa;
    private javax.swing.JTextField especialidadPsico;
    private javax.swing.JTextField id_Prepa;
    private javax.swing.JTextField id_Psico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JDialog jd_Tree;
    private javax.swing.JTree jtree;
    private javax.swing.JTextField jugadores_Psico;
    private javax.swing.JPopupMenu menuPop;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JTextField nacionalidadEntrenador;
    private javax.swing.JTextField nacionalidadJugador;
    private javax.swing.JTextField nacionalidadPrepa;
    private javax.swing.JTextField nacionalidadPsico;
    private javax.swing.JTextField nombreEntrenador;
    private javax.swing.JTextField nombreJugador;
    private javax.swing.JTextField nombrePreparador;
    private javax.swing.JTextField nombrePsico;
    private javax.swing.JTextField numeroJugador;
    private javax.swing.JMenuItem opcion_arbol;
    private javax.swing.JTextField partidosJugador;
    private javax.swing.JTextField tarjetasAmarillas;
    private javax.swing.JTextField tarjetasJugador;
    // End of variables declaration//GEN-END:variables
    ArrayList<Jugadores> jugador = new ArrayList();
    ArrayList<Preparadores> prepa = new ArrayList();
    ArrayList<Entrenadores> entrenador = new ArrayList();
    ArrayList<Psicologo> psicolo = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Jugadores juga_selec;
    Entrenadores entre_selec;
    Preparadores prepa_selec;
    Psicologo psico_selec;
}
